Add docker support
DataDog/catadog pull request #2
Opened 2024-09-12 14:35 UTC by sarahchen6

2024-09-12 14:51 UTC, lloeki requested changes
Looks good, but a cosmetic change is needed.

2024-09-12 14:51 UTC, lloeki commented on .gitignore
> +/.env
This file is lacking a newline at EOF. As a convention, we end files with newlines (unless it is not possible).

Can you fix this?

To help keep this repo consistent, I would suggest adding an [`.editorconfig` file](https://editorconfig.org/) in a separate PR; see [an example here](https://github.com/DataDog/graft-rb/blob/e657d65e8060ad0ade973ef3186c2fe1ebde2dd6/.editorconfig).

And since you're using VS Code, I would also recommend adding the [EditorConfig for VS Code extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) to your setup.

2024-09-12 14:51 UTC, lloeki commented on Dockerfile
> +ENTRYPOINT ["ruby", "/entrypoint.rb"]
This file is lacking a newline at EOF.

2024-09-12 14:51 UTC, lloeki commented on docker-compose.yaml
> +      - DD_REMOTE_CONFIGURATION_ENABLED=true
This file is lacking a newline at EOF.

2024-09-12 14:51 UTC, lloeki commented on entrypoint.rb
> +end
This file is lacking a newline at EOF.

2024-09-12 15:30 UTC, sarahchen6 commented on .gitignore
> +/.env
Just created another PR for the `.editorconfig` file.

2024-09-13 13:00 UTC, lloeki approved these changes

2024-09-13 13:00 UTC, merged